services:
  redis-master:
    container_name: redis-master
    image: redis:latest
    command: redis-server --port 6379
    ports:
      - "6379:6379"
    volumes:
      - .:/app
  redis-slave-1:
    container_name: redis-slave-1
    image: redis:latest
    command: redis-server --slaveof redis-master 6379
    volumes:
      - .:/app
    ports:
      - "7000:6379"
  redis-slave-2:
    container_name: redis-slave-2
    image: redis:latest
    command: redis-server --slaveof redis-master 6379
    volumes:
      - .:/app
    ports:
      - "7001:6379"